# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

@u1 = User.create(fname: "Sungwon", lname: "Ryu", email: "swryu0906@gmail.com", website: "http://www.codeonestop.com", git: "", password: "1234", password_confirmation: "1234")
@u2 = User.create(fname: "Anthony", lname: "Ng", email: "baruchvita.anthonyng@gmail.com", website: "", git: "", password: "1234", password_confirmation: "1234")
@u3 = User.create(fname: "Steve", lname: "Chen", email: "steve.l.chen@gmail.com", website: "", git: "", password: "1234", password_confirmation: "1234")
@u4 = User.create(fname: "Luis", lname: "Arce", email: "luisarce5@gmail.com", website: "", git: "", password: "1234", password_confirmation: "1234")
@u5 = User.create(fname: "Ace", lname: "Bi", email: "a@b.com", website: "", git: "", password: "1234", password_confirmation: "1234")
@u6 = User.create(fname: "Ceci", lname: "Di", email: "a@c.com", website: "", git: "", password: "1234", password_confirmation: "1234")



@p1 = Post.create(user: @u1, title: "Sungwon's Portfolio", link: "http://portfolio.codeonestop.com", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh.

Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices.

Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper.

Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus. Sed aliquet risus a tortor. Integer id quam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, augue. Proin sodales libero eget ante. Nulla quam. Aenean laoreet. Vestibulum nisi lectus, commodo ac, facilisis ac, ultricies eu, pede. Ut orci risus, accumsan porttitor, cursus quis, aliquet eget, justo. Sed pretium blandit orci.")
@p2 = Post.create(user: @u2, title: "Flea Market", link: "http://fleamarket.codeonestop.com", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh.

Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices.

Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper.

Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus. Sed aliquet risus a tortor. Integer id quam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, augue. Proin sodales libero eget ante. Nulla quam. Aenean laoreet. Vestibulum nisi lectus, commodo ac, facilisis ac, ultricies eu, pede. Ut orci risus, accumsan porttitor, cursus quis, aliquet eget, justo. Sed pretium blandit orci.")
@p3 = Post.create(user: @u3, title: "Restaurant Reviews", link: "http://restaurantreviews.codeonestop.com", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh.

Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices.

Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper.

Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus. Sed aliquet risus a tortor. Integer id quam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, augue. Proin sodales libero eget ante. Nulla quam. Aenean laoreet. Vestibulum nisi lectus, commodo ac, facilisis ac, ultricies eu, pede. Ut orci risus, accumsan porttitor, cursus quis, aliquet eget, justo. Sed pretium blandit orci.")


@r1 = Response.create(user:@u1, post:@p1, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r2 = Response.create(user:@u2, post:@p2, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r3 = Response.create(user:@u3, post:@p3, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r4 = Response.create(user:@u4, post:@p1, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r5 = Response.create(user:@u5, post:@p2, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r6 = Response.create(user:@u6, post:@p3, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r7 = Response.create(user:@u1, post:@p1, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r8 = Response.create(user:@u2, post:@p2, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r9 = Response.create(user:@u3, post:@p3, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r10 = Response.create(user:@u4, post:@p1, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r11 = Response.create(user:@u5, post:@p2, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
@r12 = Response.create(user:@u6, post:@p3, title: "First Response", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis posuere lacinia. Vivamus elementum accumsan ipsum, non tristique massa eleifend quis. In est dui, pellentesque posuere sagittis a, feugiat eu arcu. Phasellus risus orci, maximus eget urna in, eleifend aliquet turpis. Nulla ornare finibus nibh nec finibus. Proin interdum felis vel facilisis congue. Praesent at metus venenatis, ultrices neque tincidunt, commodo risus. Integer vulputate fringilla hendrerit. Duis laoreet nulla id imperdiet imperdiet. Cras porta tortor eu libero finibus, eu dignissim enim cursus.")
